using System.Net;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VetCare.Data;
using VetCare.Helpers;
using VetCare.Models;
using VetCare.Services;

namespace VetCare.Controllers;

[Authorize(Roles = "Administrator, Veterinarian, Clinic Staff")]
public class ReportsController : Controller
{
    private readonly VetCareDbContext _db;
    private readonly IAuditService _audit;

    public ReportsController(VetCareDbContext db, IAuditService audit)
    {
        _db = db;
        _audit = audit;
    }

    public static readonly string[] ReportTypes = { "Clinical", "Financial", "Operational" };

    public async Task<IActionResult> Index()
    {
        var reports = await _db.Reports
            .Include(r => r.Generator)
            .OrderByDescending(r => r.DateGenerated)
            .ToListAsync();
        ViewData["Title"] = "Reports";
        ViewData["DashTitle"] = "Reports & Analytics";
        return View(reports);
    }

    public IActionResult Generate()
    {
        ViewBag.ReportTypes = ReportTypes;
        ViewBag.From = DateTime.Today.AddMonths(-1).ToString("yyyy-MM-dd");
        ViewBag.To = DateTime.Today.ToString("yyyy-MM-dd");
        ViewData["DashTitle"] = "Generate Report";
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Generate(string reportType, DateTime from, DateTime to)
    {
        if (from > to)
        {
            TempData["SuccessMessage"] = "Invalid date range: 'from' must be before 'to'.";
            return RedirectToAction(nameof(Generate));
        }

        var content = reportType switch
        {
            "Clinical" => await BuildClinicalReportAsync(from, to),
            "Operational" => await BuildOperationalReportAsync(from, to),
            _ => await BuildFinancialReportAsync(from, to)
        };

        var report = new Report
        {
            ReportType = reportType,
            GeneratedBy = User.GetUserId(),
            DateGenerated = DateTime.Now,
            Content = content
        };
        _db.Reports.Add(report);
        await _db.SaveChangesAsync();
        await _audit.LogAsync("Create", "Reports", $"{reportType} report generated for {from:d} – {to:d}.");
        TempData["SuccessMessage"] = $"{reportType} report has been generated.";
        return RedirectToAction(nameof(Details), new { id = report.ReportID });
    }

    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return NotFound();
        var report = await _db.Reports
            .Include(r => r.Generator)
            .FirstOrDefaultAsync(r => r.ReportID == id);
        if (report == null) return NotFound();
        ViewData["Title"] = $"{report.ReportType} Report";
        ViewData["DashTitle"] = $"{report.ReportType} Report — {report.DateGenerated:MMM dd, yyyy}";
        return View(report);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var report = await _db.Reports.FindAsync(id);
        if (report != null)
        {
            _db.Reports.Remove(report);
            await _db.SaveChangesAsync();
            await _audit.LogAsync("Delete", "Reports", $"Report #{id} deleted.");
            TempData["SuccessMessage"] = "Report has been deleted.";
        }
        return RedirectToAction(nameof(Index));
    }

    // ---------------- Report builders ----------------

    private static string E(string? value) => WebUtility.HtmlEncode(value ?? "");

    private static string StatCard(string label, string value, string iconClass, string svg)
    {
        return $@"<div class=""stat-card"">
                <div class=""stat-icon {iconClass}"">{svg}</div>
                <div class=""stat-info""><div class=""stat-label"">{label}</div><div class=""stat-number"">{value}</div></div>
            </div>";
    }

    private static string SectionHeader(string title)
    {
        return $@"<div class=""vc-card report-section"">
            <div class=""vc-card-head""><h3 class=""vc-card-title"">{E(title)}</h3></div>
            <div class=""vc-card-body p-0 table-scroll"">";
    }

    private async Task<string> BuildClinicalReportAsync(DateTime from, DateTime to)
    {
        var appointments = await _db.Appointments
            .Include(a => a.Pet).ThenInclude(p => p!.Owner)
            .Include(a => a.Vet)
            .Include(a => a.TreatmentRecord)
            .Where(a => a.AppointmentDate.Date >= from && a.AppointmentDate.Date <= to)
            .ToListAsync();

        var sb = new StringBuilder();
        sb.AppendLine($"<div class=\"report-dateline\"><span class=\"badge-vc b-info\">Clinical</span> {from:MMM dd, yyyy} — {to:MMM dd, yyyy} · Generated by {E(User.Identity?.Name)} on {DateTime.Now:g}</div>");
        sb.AppendLine("<div class=\"stat-grid\">");
        sb.AppendLine(StatCard("Total Appointments", appointments.Count.ToString(), "si-teal", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><rect x=\"3\" y=\"4\" width=\"18\" height=\"18\" rx=\"2\"></rect><line x1=\"16\" y1=\"2\" x2=\"16\" y2=\"6\"></line><line x1=\"8\" y1=\"2\" x2=\"8\" y2=\"6\"></line><line x1=\"3\" y1=\"10\" x2=\"21\" y2=\"10\"></line></svg>"));
        sb.AppendLine(StatCard("Pending", appointments.Count(a => a.Status == "Pending").ToString(), "si-amber", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><polyline points=\"12 6 12 12 16 14\"></polyline></svg>"));
        sb.AppendLine(StatCard("Confirmed", appointments.Count(a => a.Status == "Confirmed").ToString(), "si-blue", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M22 11.08V12a10 10 0 1 1-5.93-9.14\"></path><polyline points=\"22 4 12 14.01 9 11.01\"></polyline></svg>"));
        sb.AppendLine(StatCard("Completed", appointments.Count(a => a.Status == "Completed").ToString(), "si-green", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"></path><polyline points=\"14 2 14 8 20 8\"></polyline></svg>"));
        sb.AppendLine("</div>");

        sb.AppendLine(SectionHeader("Appointments per Veterinarian"));
        sb.AppendLine("<table class=\"vc-table\"><thead><tr><th>Veterinarian</th><th>Appointments</th></tr></thead><tbody>");
        foreach (var g in appointments.GroupBy(a => a.Vet?.Name ?? "—").OrderByDescending(g => g.Count()))
            sb.AppendLine($"<tr><td class=\"cell-strong\">{E(g.Key)}</td><td>{g.Count()}</td></tr>");
        sb.AppendLine("</tbody></table></div></div>");

        sb.AppendLine(SectionHeader("Most Common Services"));
        sb.AppendLine("<table class=\"vc-table\"><thead><tr><th>#</th><th>Service</th><th>Times booked</th></tr></thead><tbody>");
        var rank = 1;
        foreach (var g in appointments.GroupBy(a => a.ServiceType).OrderByDescending(g => g.Count()).Take(5))
            sb.AppendLine($"<tr><td class=\"cell-muted\">{rank++}</td><td class=\"cell-strong\">{E(g.Key)}</td><td>{g.Count()}</td></tr>");
        sb.AppendLine("</tbody></table></div></div>");

        var completedCount = appointments.Count(a => a.Status == "Completed");
        sb.AppendLine(SectionHeader($"Completed Visits ({completedCount})"));
        sb.AppendLine("<table class=\"vc-table\"><thead><tr><th>Date</th><th>Pet</th><th>Owner</th><th>Service</th><th>Diagnosis</th></tr></thead><tbody>");
        foreach (var a in appointments.Where(a => a.Status == "Completed").OrderBy(a => a.AppointmentDate))
        {
            var dx = a.TreatmentRecord != null ? a.TreatmentRecord.Diagnosis : "No record written";
            sb.AppendLine($"<tr><td class=\"cell-muted\">{a.AppointmentDate:MMM dd}</td><td class=\"cell-strong\">{E(a.Pet?.PetName)}</td><td>{E(a.Pet?.Owner?.Name)}</td><td>{E(a.ServiceType)}</td><td>{E(dx)}</td></tr>");
        }
        sb.AppendLine("</tbody></table></div></div>");
        return sb.ToString();
    }

    private async Task<string> BuildFinancialReportAsync(DateTime from, DateTime to)
    {
        var invoices = await _db.Billings
            .Include(b => b.Owner)
            .Where(b => b.DateIssued.Date >= from && b.DateIssued.Date <= to)
            .ToListAsync();

        var billed = invoices.Sum(b => b.TotalAmount);
        var collected = invoices.Where(b => b.PaymentStatus == "Paid").Sum(b => b.TotalAmount);
        var pending = invoices.Where(b => b.PaymentStatus == "Pending").Sum(b => b.TotalAmount);

        var sb = new StringBuilder();
        sb.AppendLine($"<div class=\"report-dateline\"><span class=\"badge-vc b-paid\">Financial</span> {from:MMM dd, yyyy} — {to:MMM dd, yyyy} · Generated by {E(User.Identity?.Name)} on {DateTime.Now:g}</div>");
        sb.AppendLine("<div class=\"stat-grid\">");
        sb.AppendLine(StatCard("Invoices Issued", invoices.Count.ToString(), "si-purple", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z\"></path><polyline points=\"14 2 14 8 20 8\"></polyline><line x1=\"16\" y1=\"13\" x2=\"8\" y2=\"13\"></line><line x1=\"16\" y1=\"17\" x2=\"8\" y2=\"17\"></line></svg>"));
        sb.AppendLine(StatCard("Total Billed", $"₱{billed:N2}", "si-teal", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><rect x=\"2\" y=\"5\" width=\"20\" height=\"14\" rx=\"2\"></rect><line x1=\"2\" y1=\"10\" x2=\"22\" y2=\"10\"></line></svg>"));
        sb.AppendLine(StatCard("Total Collected (Paid)", $"₱{collected:N2}", "si-green", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M12 1v22\"></path><path d=\"M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6\"></path></svg>"));
        sb.AppendLine(StatCard("Pending Receivables", $"₱{pending:N2}", "si-amber", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><polyline points=\"12 6 12 12 16 14\"></polyline></svg>"));
        sb.AppendLine("</div>");

        sb.AppendLine(SectionHeader("By Payment Method (Collected)"));
        sb.AppendLine("<table class=\"vc-table\"><thead><tr><th>Method</th><th>Collected</th></tr></thead><tbody>");
        foreach (var g in invoices.Where(b => b.PaymentStatus == "Paid").GroupBy(b => b.PaymentMethod).OrderByDescending(g => g.Sum(b => b.TotalAmount)))
            sb.AppendLine($"<tr><td class=\"cell-strong\">{E(g.Key)}</td><td>₱{g.Sum(b => b.TotalAmount):N2}</td></tr>");
        if (!invoices.Any(b => b.PaymentStatus == "Paid"))
            sb.AppendLine("<tr><td colspan=\"2\" class=\"cell-muted\">No collected payments in this period.</td></tr>");
        sb.AppendLine("</tbody></table></div></div>");

        sb.AppendLine(SectionHeader("Invoice List"));
        sb.AppendLine("<table class=\"vc-table\"><thead><tr><th>Invoice</th><th>Date</th><th>Owner</th><th>Amount</th><th>Status</th></tr></thead><tbody>");
        foreach (var b in invoices.OrderBy(b => b.DateIssued))
        {
            var badge = b.PaymentStatus == "Paid" ? "b-paid" : "b-pending";
            sb.AppendLine($"<tr><td class=\"cell-strong\">#INV-{b.InvoiceID:D4}</td><td class=\"cell-muted\">{b.DateIssued:MMM dd}</td><td>{E(b.Owner?.Name)}</td><td>₱{b.TotalAmount:N2}</td><td><span class=\"badge-vc {badge}\">{E(b.PaymentStatus)}</span></td></tr>");
        }
        if (!invoices.Any())
            sb.AppendLine("<tr><td colspan=\"5\" class=\"cell-muted\">No invoices issued in this period.</td></tr>");
        sb.AppendLine("</tbody></table></div></div>");
        return sb.ToString();
    }

    private async Task<string> BuildOperationalReportAsync(DateTime from, DateTime to)
    {
        var items = await _db.InventoryItems.Include(i => i.Supplier).ToListAsync();
        var lowStock = items.Where(i => i.Quantity <= i.ReorderLevel).ToList();
        var reminders = await _db.VaccinationReminders
            .Include(v => v.Pet)
            .Where(v => v.DueDate.Date >= from && v.DueDate.Date <= to)
            .ToListAsync();
        var inventoryValue = items.Sum(i => i.Quantity * i.UnitPrice);

        var sb = new StringBuilder();
        sb.AppendLine($"<div class=\"report-dateline\"><span class=\"badge-vc b-pending\">Operational</span> {from:MMM dd, yyyy} — {to:MMM dd, yyyy} · Generated by {E(User.Identity?.Name)} on {DateTime.Now:g}</div>");
        sb.AppendLine("<div class=\"stat-grid\">");
        sb.AppendLine(StatCard("Inventory Items", items.Count.ToString(), "si-blue", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z\"></path></svg>"));
        sb.AppendLine(StatCard("Total Inventory Value", $"₱{inventoryValue:N2}", "si-teal", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M12 1v22\"></path><path d=\"M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6\"></path></svg>"));
        sb.AppendLine(StatCard("Low Stock Items", lowStock.Count.ToString(), "si-red", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><circle cx=\"12\" cy=\"12\" r=\"10\"></circle><line x1=\"12\" y1=\"8\" x2=\"12\" y2=\"12\"></line><line x1=\"12\" y1=\"16\" x2=\"12.01\" y2=\"16\"></line></svg>"));
        sb.AppendLine(StatCard("Vaccination Reminders Due", reminders.Count.ToString(), "si-purple", "<svg width=\"22\" height=\"22\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\"><path d=\"M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9\"></path><path d=\"M13.73 21a2 2 0 0 1-3.46 0\"></path></svg>"));
        sb.AppendLine("</div>");

        if (lowStock.Any())
        {
            sb.AppendLine(SectionHeader("Reorder Now"));
            sb.AppendLine("<table class=\"vc-table\"><thead><tr><th>Item</th><th>Quantity Left</th><th>Reorder Level</th><th>Supplier</th></tr></thead><tbody>");
            foreach (var i in lowStock.OrderBy(i => i.Quantity))
                sb.AppendLine($"<tr><td class=\"cell-strong\">{E(i.ItemName)}</td><td><span class=\"badge-vc b-low\">{i.Quantity} left</span></td><td class=\"cell-muted\">{i.ReorderLevel}</td><td>{E(i.Supplier?.SupplierName ?? "—")}</td></tr>");
            sb.AppendLine("</tbody></table></div></div>");
        }

        sb.AppendLine(SectionHeader("Stock Levels"));
        sb.AppendLine("<table class=\"vc-table\"><thead><tr><th>Item</th><th>Quantity</th><th>Unit Price</th><th>Stock Value</th></tr></thead><tbody>");
        if (items.Any())
        {
            foreach (var i in items.OrderBy(i => i.ItemName))
                sb.AppendLine($"<tr><td class=\"cell-strong\">{E(i.ItemName)}</td><td>{i.Quantity}</td><td>₱{i.UnitPrice:N2}</td><td>₱{i.Quantity * i.UnitPrice:N2}</td></tr>");
        }
        else
        {
            sb.AppendLine("<tr><td colspan=\"4\" class=\"cell-muted\">No inventory items on record.</td></tr>");
        }
        sb.AppendLine("</tbody></table></div></div>");

        if (reminders.Any())
        {
            sb.AppendLine(SectionHeader("Vaccination Reminders Due"));
            sb.AppendLine("<table class=\"vc-table\"><thead><tr><th>Pet</th><th>Due Date</th><th>Status</th></tr></thead><tbody>");
            foreach (var r in reminders.OrderBy(r => r.DueDate))
            {
                var badge = r.Status == "Sent" ? "b-sent" : r.Status == "Completed" ? "b-paid" : "b-pending";
                sb.AppendLine($"<tr><td class=\"cell-strong\">{E(r.Pet?.PetName)}</td><td class=\"cell-muted\">{r.DueDate:MMM dd, yyyy}</td><td><span class=\"badge-vc {badge}\">{E(r.Status)}</span></td></tr>");
            }
            sb.AppendLine("</tbody></table></div></div>");
        }

        return sb.ToString();
    }
}
