using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using VetCare.Data;
using VetCare.Helpers;
using VetCare.Models;
using VetCare.Services;

namespace VetCare.Controllers;

[Authorize(Roles = "Administrator, Veterinarian, Clinic Staff")]
public class ReportsController : Controller
{
    private readonly VetCareDbContext _db;
    private readonly IAuditService _audit;

    public ReportsController(VetCareDbContext db, IAuditService audit)
    {
        _db = db;
        _audit = audit;
    }

    public static readonly string[] ReportTypes = { "Clinical", "Financial", "Operational" };

    public async Task<IActionResult> Index()
    {
        var reports = await _db.Reports
            .Include(r => r.Generator)
            .OrderByDescending(r => r.DateGenerated)
            .ToListAsync();
        ViewData["Title"] = "Reports";
        ViewData["DashTitle"] = "Reports & Analytics";
        return View(reports);
    }

    public IActionResult Generate()
    {
        ViewBag.ReportTypes = ReportTypes;
        ViewBag.From = DateTime.Today.AddMonths(-1).ToString("yyyy-MM-dd");
        ViewBag.To = DateTime.Today.ToString("yyyy-MM-dd");
        ViewData["DashTitle"] = "Generate Report";
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Generate(string reportType, DateTime from, DateTime to)
    {
        if (from > to)
        {
            TempData["SuccessMessage"] = "Invalid date range: 'from' must be before 'to'.";
            return RedirectToAction(nameof(Generate));
        }

        var content = reportType switch
        {
            "Clinical" => await BuildClinicalReportAsync(from, to),
            "Operational" => await BuildOperationalReportAsync(from, to),
            _ => await BuildFinancialReportAsync(from, to)
        };

        var report = new Report
        {
            ReportType = reportType,
            GeneratedBy = User.GetUserId(),
            DateGenerated = DateTime.Now,
            Content = content
        };
        _db.Reports.Add(report);
        await _db.SaveChangesAsync();
        await _audit.LogAsync("Create", "Reports", $"{reportType} report generated for {from:d} – {to:d}.");
        TempData["SuccessMessage"] = $"{reportType} report has been generated.";
        return RedirectToAction(nameof(Details), new { id = report.ReportID });
    }

    public async Task<IActionResult> Details(int? id)
    {
        if (id == null) return NotFound();
        var report = await _db.Reports
            .Include(r => r.Generator)
            .FirstOrDefaultAsync(r => r.ReportID == id);
        if (report == null) return NotFound();
        ViewData["Title"] = $"{report.ReportType} Report";
        ViewData["DashTitle"] = $"{report.ReportType} Report — {report.DateGenerated:MMM dd, yyyy}";
        return View(report);
    }

    [Authorize(Roles = "Administrator")]
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var report = await _db.Reports.FindAsync(id);
        if (report != null)
        {
            _db.Reports.Remove(report);
            await _db.SaveChangesAsync();
            await _audit.LogAsync("Delete", "Reports", $"Report #{id} deleted.");
            TempData["SuccessMessage"] = "Report has been deleted.";
        }
        return RedirectToAction(nameof(Index));
    }

    // ---------------- Report builders ----------------

    private async Task<string> BuildClinicalReportAsync(DateTime from, DateTime to)
    {
        var appointments = await _db.Appointments
            .Include(a => a.Pet).ThenInclude(p => p!.Owner)
            .Include(a => a.Vet)
            .Include(a => a.TreatmentRecord)
            .Where(a => a.AppointmentDate.Date >= from && a.AppointmentDate.Date <= to)
            .ToListAsync();

        var sb = new StringBuilder();
        sb.AppendLine($"CLINICAL REPORT — {from:MMM dd, yyyy} to {to:MMM dd, yyyy}");
        sb.AppendLine($"Generated by {User.Identity?.Name} on {DateTime.Now:g}");
        sb.AppendLine(new string('=', 60));
        sb.AppendLine($"Total appointments:        {appointments.Count}");
        sb.AppendLine($"  Pending:                 {appointments.Count(a => a.Status == "Pending")}");
        sb.AppendLine($"  Confirmed:               {appointments.Count(a => a.Status == "Confirmed")}");
        sb.AppendLine($"  Completed:               {appointments.Count(a => a.Status == "Completed")}");
        sb.AppendLine($"  Cancelled:               {appointments.Count(a => a.Status == "Cancelled")}");
        sb.AppendLine($"Treatment records written: {appointments.Count(a => a.TreatmentRecord != null)}");
        sb.AppendLine();
        sb.AppendLine("APPOINTMENTS PER VETERINARIAN");
        foreach (var g in appointments.GroupBy(a => a.Vet?.Name ?? "—").OrderByDescending(g => g.Count()))
            sb.AppendLine($"  {g.Key,-28} {g.Count()} appointment(s)");
        sb.AppendLine();
        sb.AppendLine("MOST COMMON SERVICES");
        foreach (var g in appointments.GroupBy(a => a.ServiceType).OrderByDescending(g => g.Count()).Take(5))
            sb.AppendLine($"  {g.Key,-28} {g.Count()} time(s)");
        sb.AppendLine();
        sb.AppendLine("COMPLETED VISITS");
        foreach (var a in appointments.Where(a => a.Status == "Completed").OrderBy(a => a.AppointmentDate))
        {
            var dx = a.TreatmentRecord != null ? a.TreatmentRecord.Diagnosis : "no record";
            sb.AppendLine($"  [{a.AppointmentDate:MMM dd}] {a.Pet?.PetName} ({a.Pet?.Owner?.Name}) — {a.ServiceType} — {dx}");
        }
        return sb.ToString();
    }

    private async Task<string> BuildFinancialReportAsync(DateTime from, DateTime to)
    {
        var invoices = await _db.Billings
            .Include(b => b.Owner)
            .Where(b => b.DateIssued.Date >= from && b.DateIssued.Date <= to)
            .ToListAsync();

        var billed = invoices.Sum(b => b.TotalAmount);
        var collected = invoices.Where(b => b.PaymentStatus == "Paid").Sum(b => b.TotalAmount);
        var pending = invoices.Where(b => b.PaymentStatus == "Pending").Sum(b => b.TotalAmount);

        var sb = new StringBuilder();
        sb.AppendLine($"FINANCIAL REPORT — {from:MMM dd, yyyy} to {to:MMM dd, yyyy}");
        sb.AppendLine($"Generated by {User.Identity?.Name} on {DateTime.Now:g}");
        sb.AppendLine(new string('=', 60));
        sb.AppendLine($"Invoices issued:           {invoices.Count}");
        sb.AppendLine($"Total billed:              ₱{billed:N2}");
        sb.AppendLine($"Total collected (paid):    ₱{collected:N2}");
        sb.AppendLine($"Pending receivables:       ₱{pending:N2}");
        sb.AppendLine($"Collection rate:           {(billed > 0 ? collected / billed * 100m : 0):F1}%");
        sb.AppendLine();
        sb.AppendLine("BY PAYMENT METHOD (collected)");
        foreach (var g in invoices.Where(b => b.PaymentStatus == "Paid").GroupBy(b => b.PaymentMethod))
            sb.AppendLine($"  {g.Key,-28} ₱{g.Sum(b => b.TotalAmount):N2}");
        sb.AppendLine();
        sb.AppendLine("INVOICE LIST");
        foreach (var b in invoices.OrderBy(b => b.DateIssued))
            sb.AppendLine($"  #INV-{b.InvoiceID:D4} [{b.DateIssued:MMM dd}] {b.Owner?.Name,-22} ₱{b.TotalAmount,10:N2}  {b.PaymentStatus}");
        return sb.ToString();
    }

    private async Task<string> BuildOperationalReportAsync(DateTime from, DateTime to)
    {
        var items = await _db.InventoryItems.Include(i => i.Supplier).ToListAsync();
        var lowStock = items.Where(i => i.Quantity <= i.ReorderLevel).ToList();
        var reminders = await _db.VaccinationReminders
            .Include(v => v.Pet)
            .Where(v => v.DueDate.Date >= from && v.DueDate.Date <= to)
            .ToListAsync();
        var inventoryValue = items.Sum(i => i.Quantity * i.UnitPrice);

        var sb = new StringBuilder();
        sb.AppendLine($"OPERATIONAL REPORT — {from:MMM dd, yyyy} to {to:MMM dd, yyyy}");
        sb.AppendLine($"Generated by {User.Identity?.Name} on {DateTime.Now:g}");
        sb.AppendLine(new string('=', 60));
        sb.AppendLine($"Inventory items:           {items.Count}");
        sb.AppendLine($"Total inventory value:     ₱{inventoryValue:N2}");
        sb.AppendLine($"Low stock items:           {lowStock.Count}");
        sb.AppendLine($"Vaccination reminders due: {reminders.Count} ({reminders.Count(r => r.Status == "Sent")} sent, {reminders.Count(r => r.Status == "Pending")} pending)");
        sb.AppendLine();
        if (lowStock.Any())
        {
            sb.AppendLine("REORDER NOW");
            foreach (var i in lowStock.OrderBy(i => i.Quantity))
                sb.AppendLine($"  {i.ItemName,-32} {i.Quantity,4} left (reorder at {i.ReorderLevel}) — supplier: {i.Supplier?.SupplierName ?? "—"}");
            sb.AppendLine();
        }
        sb.AppendLine("STOCK LEVELS");
        foreach (var i in items.OrderBy(i => i.ItemName))
            sb.AppendLine($"  {i.ItemName,-32} {i.Quantity,5} units @ ₱{i.UnitPrice:N2}");
        return sb.ToString();
    }
}
